- name: Install git
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: Install apps for lighthouse
  become: true
  ansible.builtin.yum:
    name:
      - epel-release
      - nginx